// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/conf.proto

// protoc --java_out=plugins=grpc:. api/*.proto
// protoc --go_out=plugins=grpc:. api/*.proto

package api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Conf 数据库引擎对象
type Conf struct {
	Port                     string   `protobuf:"bytes,1,opt,name=Port,proto3" json:"Port,omitempty"`
	RootDir                  string   `protobuf:"bytes,2,opt,name=RootDir,proto3" json:"RootDir,omitempty"`
	DataDir                  string   `protobuf:"bytes,3,opt,name=DataDir,proto3" json:"DataDir,omitempty"`
	LogDir                   string   `protobuf:"bytes,4,opt,name=LogDir,proto3" json:"LogDir,omitempty"`
	LimitOpenFile            int32    `protobuf:"varint,5,opt,name=LimitOpenFile,proto3" json:"LimitOpenFile,omitempty"`
	TLS                      bool     `protobuf:"varint,6,opt,name=TLS,proto3" json:"TLS,omitempty"`
	TLSServerKeyFile         string   `protobuf:"bytes,7,opt,name=TLSServerKeyFile,proto3" json:"TLSServerKeyFile,omitempty"`
	TLSServerCertFile        string   `protobuf:"bytes,8,opt,name=TLSServerCertFile,proto3" json:"TLSServerCertFile,omitempty"`
	Limit                    bool     `protobuf:"varint,9,opt,name=Limit,proto3" json:"Limit,omitempty"`
	LimitMillisecond         int32    `protobuf:"varint,10,opt,name=LimitMillisecond,proto3" json:"LimitMillisecond,omitempty"`
	LimitCount               int32    `protobuf:"varint,11,opt,name=LimitCount,proto3" json:"LimitCount,omitempty"`
	LimitIntervalMillisecond int32    `protobuf:"varint,12,opt,name=LimitIntervalMillisecond,proto3" json:"LimitIntervalMillisecond,omitempty"`
	LilyLockFilePath         string   `protobuf:"bytes,13,opt,name=LilyLockFilePath,proto3" json:"LilyLockFilePath,omitempty"`
	LilyBootstrapFilePath    string   `protobuf:"bytes,14,opt,name=LilyBootstrapFilePath,proto3" json:"LilyBootstrapFilePath,omitempty"`
	XXX_NoUnkeyedLiteral     struct{} `json:"-"`
	XXX_unrecognized         []byte   `json:"-"`
	XXX_sizecache            int32    `json:"-"`
}

func (m *Conf) Reset()         { *m = Conf{} }
func (m *Conf) String() string { return proto.CompactTextString(m) }
func (*Conf) ProtoMessage()    {}
func (*Conf) Descriptor() ([]byte, []int) {
	return fileDescriptor_deb6b35ebbfdf874, []int{0}
}

func (m *Conf) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Conf.Unmarshal(m, b)
}
func (m *Conf) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Conf.Marshal(b, m, deterministic)
}
func (m *Conf) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Conf.Merge(m, src)
}
func (m *Conf) XXX_Size() int {
	return xxx_messageInfo_Conf.Size(m)
}
func (m *Conf) XXX_DiscardUnknown() {
	xxx_messageInfo_Conf.DiscardUnknown(m)
}

var xxx_messageInfo_Conf proto.InternalMessageInfo

func (m *Conf) GetPort() string {
	if m != nil {
		return m.Port
	}
	return ""
}

func (m *Conf) GetRootDir() string {
	if m != nil {
		return m.RootDir
	}
	return ""
}

func (m *Conf) GetDataDir() string {
	if m != nil {
		return m.DataDir
	}
	return ""
}

func (m *Conf) GetLogDir() string {
	if m != nil {
		return m.LogDir
	}
	return ""
}

func (m *Conf) GetLimitOpenFile() int32 {
	if m != nil {
		return m.LimitOpenFile
	}
	return 0
}

func (m *Conf) GetTLS() bool {
	if m != nil {
		return m.TLS
	}
	return false
}

func (m *Conf) GetTLSServerKeyFile() string {
	if m != nil {
		return m.TLSServerKeyFile
	}
	return ""
}

func (m *Conf) GetTLSServerCertFile() string {
	if m != nil {
		return m.TLSServerCertFile
	}
	return ""
}

func (m *Conf) GetLimit() bool {
	if m != nil {
		return m.Limit
	}
	return false
}

func (m *Conf) GetLimitMillisecond() int32 {
	if m != nil {
		return m.LimitMillisecond
	}
	return 0
}

func (m *Conf) GetLimitCount() int32 {
	if m != nil {
		return m.LimitCount
	}
	return 0
}

func (m *Conf) GetLimitIntervalMillisecond() int32 {
	if m != nil {
		return m.LimitIntervalMillisecond
	}
	return 0
}

func (m *Conf) GetLilyLockFilePath() string {
	if m != nil {
		return m.LilyLockFilePath
	}
	return ""
}

func (m *Conf) GetLilyBootstrapFilePath() string {
	if m != nil {
		return m.LilyBootstrapFilePath
	}
	return ""
}

func init() {
	proto.RegisterType((*Conf)(nil), "api.Conf")
}

func init() { proto.RegisterFile("api/conf.proto", fileDescriptor_deb6b35ebbfdf874) }

var fileDescriptor_deb6b35ebbfdf874 = []byte{
	// 320 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0x4f, 0x4b, 0x33, 0x31,
	0x10, 0xc6, 0xd9, 0x77, 0xfb, 0x77, 0x5e, 0x5b, 0xea, 0xa0, 0x92, 0x93, 0x16, 0xf1, 0x50, 0x44,
	0xd6, 0x83, 0x9e, 0x3c, 0xb6, 0x45, 0x10, 0x57, 0x2c, 0xdb, 0x7e, 0x81, 0x74, 0x4d, 0x35, 0x18,
	0x33, 0x4b, 0x1a, 0x0b, 0xfd, 0xe6, 0x1e, 0x25, 0xb3, 0xb5, 0x54, 0x57, 0x6f, 0xf3, 0xfc, 0x9e,
	0x67, 0x32, 0x13, 0x18, 0xe8, 0xca, 0x42, 0x5f, 0xe6, 0x64, 0x17, 0x49, 0xe1, 0xc8, 0x13, 0xc6,
	0xb2, 0xd0, 0xa7, 0x1f, 0x31, 0xd4, 0x46, 0x64, 0x17, 0x88, 0x50, 0x9b, 0x90, 0xf3, 0x22, 0xea,
	0x47, 0x83, 0x76, 0xc6, 0x35, 0x0a, 0x68, 0x66, 0x44, 0x7e, 0xac, 0x9d, 0xf8, 0xc7, 0xf8, 0x4b,
	0x06, 0x67, 0x2c, 0xbd, 0x0c, 0x4e, 0x5c, 0x3a, 0x1b, 0x89, 0x47, 0xd0, 0x48, 0xe9, 0x39, 0x18,
	0x35, 0x36, 0x36, 0x0a, 0xcf, 0xa0, 0x93, 0xea, 0x37, 0xed, 0x1f, 0x0b, 0x65, 0x6f, 0xb5, 0x51,
	0xa2, 0xde, 0x8f, 0x06, 0xf5, 0xec, 0x3b, 0xc4, 0x1e, 0xc4, 0xb3, 0x74, 0x2a, 0x1a, 0xfd, 0x68,
	0xd0, 0xca, 0x42, 0x89, 0xe7, 0xd0, 0x9b, 0xa5, 0xd3, 0xa9, 0x72, 0x2b, 0xe5, 0xee, 0xd5, 0x9a,
	0x5b, 0x9b, 0xfc, 0x72, 0x85, 0xe3, 0x05, 0xec, 0x6f, 0xd9, 0x48, 0x39, 0xcf, 0xe1, 0x16, 0x87,
	0xab, 0x06, 0x1e, 0x40, 0x9d, 0x87, 0x8b, 0x36, 0x4f, 0x2b, 0x45, 0x98, 0xc7, 0xc5, 0x83, 0x36,
	0x46, 0x2f, 0x55, 0x4e, 0xf6, 0x49, 0x00, 0xaf, 0x5a, 0xe1, 0x78, 0x0c, 0xc0, 0x6c, 0x44, 0xef,
	0xd6, 0x8b, 0xff, 0x9c, 0xda, 0x21, 0x78, 0x03, 0x82, 0xd5, 0x9d, 0xf5, 0xca, 0xad, 0xa4, 0xd9,
	0x7d, 0x73, 0x8f, 0xd3, 0x7f, 0xfa, 0xe5, 0x1e, 0x66, 0x9d, 0x52, 0xfe, 0x1a, 0xb6, 0x9d, 0x48,
	0xff, 0x22, 0x3a, 0xe5, 0xbf, 0x7f, 0x72, 0xbc, 0x86, 0xc3, 0xc0, 0x86, 0x44, 0x7e, 0xe9, 0x9d,
	0x2c, 0xb6, 0x0d, 0x5d, 0x6e, 0xf8, 0xdd, 0x1c, 0x9e, 0x00, 0xe6, 0x36, 0x91, 0x73, 0xe5, 0x74,
	0x9e, 0x18, 0x6d, 0xd6, 0x89, 0x2c, 0xf4, 0xb0, 0x1d, 0xae, 0x61, 0x12, 0x0e, 0x64, 0xde, 0xe0,
	0x3b, 0xb9, 0xfa, 0x0c, 0x00, 0x00, 0xff, 0xff, 0x5d, 0x9b, 0x2f, 0xc1, 0x39, 0x02, 0x00, 0x00,
}
