// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/data.proto

// protoc --java_out=plugins=grpc:. api/*.proto
// protoc --go_out=plugins=grpc:. api/*.proto

package api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// FormType 表类型
type FormType int32

const (
	FormType_SQL FormType = 0
	FormType_Doc FormType = 1
)

var FormType_name = map[int32]string{
	0: "SQL",
	1: "Doc",
}

var FormType_value = map[string]int32{
	"SQL": 0,
	"Doc": 1,
}

func (x FormType) String() string {
	return proto.EnumName(FormType_name, int32(x))
}

func (FormType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_51ac7b4dd81eed94, []int{0}
}

// Lily 数据库引擎对象
type Lily struct {
	Databases            map[string]*Database `protobuf:"bytes,1,rep,name=databases,proto3" json:"databases,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Lily) Reset()         { *m = Lily{} }
func (m *Lily) String() string { return proto.CompactTextString(m) }
func (*Lily) ProtoMessage()    {}
func (*Lily) Descriptor() ([]byte, []int) {
	return fileDescriptor_51ac7b4dd81eed94, []int{0}
}

func (m *Lily) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Lily.Unmarshal(m, b)
}
func (m *Lily) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Lily.Marshal(b, m, deterministic)
}
func (m *Lily) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Lily.Merge(m, src)
}
func (m *Lily) XXX_Size() int {
	return xxx_messageInfo_Lily.Size(m)
}
func (m *Lily) XXX_DiscardUnknown() {
	xxx_messageInfo_Lily.DiscardUnknown(m)
}

var xxx_messageInfo_Lily proto.InternalMessageInfo

func (m *Lily) GetDatabases() map[string]*Database {
	if m != nil {
		return m.Databases
	}
	return nil
}

// Database 数据库对象
type Database struct {
	Id                   string           `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string           `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Comment              string           `protobuf:"bytes,3,opt,name=comment,proto3" json:"comment,omitempty"`
	Forms                map[string]*Form `protobuf:"bytes,4,rep,name=forms,proto3" json:"forms,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Database) Reset()         { *m = Database{} }
func (m *Database) String() string { return proto.CompactTextString(m) }
func (*Database) ProtoMessage()    {}
func (*Database) Descriptor() ([]byte, []int) {
	return fileDescriptor_51ac7b4dd81eed94, []int{1}
}

func (m *Database) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Database.Unmarshal(m, b)
}
func (m *Database) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Database.Marshal(b, m, deterministic)
}
func (m *Database) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Database.Merge(m, src)
}
func (m *Database) XXX_Size() int {
	return xxx_messageInfo_Database.Size(m)
}
func (m *Database) XXX_DiscardUnknown() {
	xxx_messageInfo_Database.DiscardUnknown(m)
}

var xxx_messageInfo_Database proto.InternalMessageInfo

func (m *Database) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Database) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Database) GetComment() string {
	if m != nil {
		return m.Comment
	}
	return ""
}

func (m *Database) GetForms() map[string]*Form {
	if m != nil {
		return m.Forms
	}
	return nil
}

// Form 数据库表对象
type Form struct {
	Id                   string            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string            `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Comment              string            `protobuf:"bytes,3,opt,name=comment,proto3" json:"comment,omitempty"`
	FormType             FormType          `protobuf:"varint,4,opt,name=formType,proto3,enum=api.FormType" json:"formType,omitempty"`
	Indexes              map[string]*Index `protobuf:"bytes,5,rep,name=indexes,proto3" json:"indexes,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Form) Reset()         { *m = Form{} }
func (m *Form) String() string { return proto.CompactTextString(m) }
func (*Form) ProtoMessage()    {}
func (*Form) Descriptor() ([]byte, []int) {
	return fileDescriptor_51ac7b4dd81eed94, []int{2}
}

func (m *Form) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Form.Unmarshal(m, b)
}
func (m *Form) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Form.Marshal(b, m, deterministic)
}
func (m *Form) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Form.Merge(m, src)
}
func (m *Form) XXX_Size() int {
	return xxx_messageInfo_Form.Size(m)
}
func (m *Form) XXX_DiscardUnknown() {
	xxx_messageInfo_Form.DiscardUnknown(m)
}

var xxx_messageInfo_Form proto.InternalMessageInfo

func (m *Form) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Form) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Form) GetComment() string {
	if m != nil {
		return m.Comment
	}
	return ""
}

func (m *Form) GetFormType() FormType {
	if m != nil {
		return m.FormType
	}
	return FormType_SQL
}

func (m *Form) GetIndexes() map[string]*Index {
	if m != nil {
		return m.Indexes
	}
	return nil
}

// Index 索引对象
type Index struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Primary              bool     `protobuf:"varint,2,opt,name=primary,proto3" json:"primary,omitempty"`
	KeyStructure         string   `protobuf:"bytes,3,opt,name=keyStructure,proto3" json:"keyStructure,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Index) Reset()         { *m = Index{} }
func (m *Index) String() string { return proto.CompactTextString(m) }
func (*Index) ProtoMessage()    {}
func (*Index) Descriptor() ([]byte, []int) {
	return fileDescriptor_51ac7b4dd81eed94, []int{3}
}

func (m *Index) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Index.Unmarshal(m, b)
}
func (m *Index) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Index.Marshal(b, m, deterministic)
}
func (m *Index) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Index.Merge(m, src)
}
func (m *Index) XXX_Size() int {
	return xxx_messageInfo_Index.Size(m)
}
func (m *Index) XXX_DiscardUnknown() {
	xxx_messageInfo_Index.DiscardUnknown(m)
}

var xxx_messageInfo_Index proto.InternalMessageInfo

func (m *Index) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Index) GetPrimary() bool {
	if m != nil {
		return m.Primary
	}
	return false
}

func (m *Index) GetKeyStructure() string {
	if m != nil {
		return m.KeyStructure
	}
	return ""
}

// Selector 检索选择器
type Selector struct {
	Conditions           []*Condition `protobuf:"bytes,1,rep,name=conditions,proto3" json:"conditions,omitempty"`
	Skip                 int32        `protobuf:"varint,2,opt,name=skip,proto3" json:"skip,omitempty"`
	Sort                 *Sort        `protobuf:"bytes,3,opt,name=sort,proto3" json:"sort,omitempty"`
	Limit                int32        `protobuf:"varint,4,opt,name=Limit,proto3" json:"Limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Selector) Reset()         { *m = Selector{} }
func (m *Selector) String() string { return proto.CompactTextString(m) }
func (*Selector) ProtoMessage()    {}
func (*Selector) Descriptor() ([]byte, []int) {
	return fileDescriptor_51ac7b4dd81eed94, []int{4}
}

func (m *Selector) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Selector.Unmarshal(m, b)
}
func (m *Selector) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Selector.Marshal(b, m, deterministic)
}
func (m *Selector) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Selector.Merge(m, src)
}
func (m *Selector) XXX_Size() int {
	return xxx_messageInfo_Selector.Size(m)
}
func (m *Selector) XXX_DiscardUnknown() {
	xxx_messageInfo_Selector.DiscardUnknown(m)
}

var xxx_messageInfo_Selector proto.InternalMessageInfo

func (m *Selector) GetConditions() []*Condition {
	if m != nil {
		return m.Conditions
	}
	return nil
}

func (m *Selector) GetSkip() int32 {
	if m != nil {
		return m.Skip
	}
	return 0
}

func (m *Selector) GetSort() *Sort {
	if m != nil {
		return m.Sort
	}
	return nil
}

func (m *Selector) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

// Condition 条件查询
type Condition struct {
	// param 参数名，由对象结构层级字段通过'.'组成，如
	//
	// ref := &ref{
	//		i: 1,
	//		s: "2",
	//		in: refIn{
	//			i: 3,
	//			s: "4",
	//		},
	//	}
	//
	// key可取'i','in.s'
	Param                string   `protobuf:"bytes,1,opt,name=param,proto3" json:"param,omitempty"`
	Cond                 string   `protobuf:"bytes,2,opt,name=cond,proto3" json:"cond,omitempty"`
	Value                []byte   `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Condition) Reset()         { *m = Condition{} }
func (m *Condition) String() string { return proto.CompactTextString(m) }
func (*Condition) ProtoMessage()    {}
func (*Condition) Descriptor() ([]byte, []int) {
	return fileDescriptor_51ac7b4dd81eed94, []int{5}
}

func (m *Condition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Condition.Unmarshal(m, b)
}
func (m *Condition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Condition.Marshal(b, m, deterministic)
}
func (m *Condition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Condition.Merge(m, src)
}
func (m *Condition) XXX_Size() int {
	return xxx_messageInfo_Condition.Size(m)
}
func (m *Condition) XXX_DiscardUnknown() {
	xxx_messageInfo_Condition.DiscardUnknown(m)
}

var xxx_messageInfo_Condition proto.InternalMessageInfo

func (m *Condition) GetParam() string {
	if m != nil {
		return m.Param
	}
	return ""
}

func (m *Condition) GetCond() string {
	if m != nil {
		return m.Cond
	}
	return ""
}

func (m *Condition) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

// Sort 排序方式
type Sort struct {
	// param 参数名，由对象结构层级字段通过'.'组成，如
	//
	// ref := &ref{
	//		i: 1,
	//		s: "2",
	//		in: refIn{
	//			i: 3,
	//			s: "4",
	//		},
	//	}
	//
	// key可取'i','in.s'
	Param                string   `protobuf:"bytes,1,opt,name=param,proto3" json:"param,omitempty"`
	Asc                  bool     `protobuf:"varint,2,opt,name=asc,proto3" json:"asc,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Sort) Reset()         { *m = Sort{} }
func (m *Sort) String() string { return proto.CompactTextString(m) }
func (*Sort) ProtoMessage()    {}
func (*Sort) Descriptor() ([]byte, []int) {
	return fileDescriptor_51ac7b4dd81eed94, []int{6}
}

func (m *Sort) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Sort.Unmarshal(m, b)
}
func (m *Sort) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Sort.Marshal(b, m, deterministic)
}
func (m *Sort) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Sort.Merge(m, src)
}
func (m *Sort) XXX_Size() int {
	return xxx_messageInfo_Sort.Size(m)
}
func (m *Sort) XXX_DiscardUnknown() {
	xxx_messageInfo_Sort.DiscardUnknown(m)
}

var xxx_messageInfo_Sort proto.InternalMessageInfo

func (m *Sort) GetParam() string {
	if m != nil {
		return m.Param
	}
	return ""
}

func (m *Sort) GetAsc() bool {
	if m != nil {
		return m.Asc
	}
	return false
}

func init() {
	proto.RegisterEnum("api.FormType", FormType_name, FormType_value)
	proto.RegisterType((*Lily)(nil), "api.Lily")
	proto.RegisterMapType((map[string]*Database)(nil), "api.Lily.DatabasesEntry")
	proto.RegisterType((*Database)(nil), "api.Database")
	proto.RegisterMapType((map[string]*Form)(nil), "api.Database.FormsEntry")
	proto.RegisterType((*Form)(nil), "api.Form")
	proto.RegisterMapType((map[string]*Index)(nil), "api.Form.IndexesEntry")
	proto.RegisterType((*Index)(nil), "api.Index")
	proto.RegisterType((*Selector)(nil), "api.Selector")
	proto.RegisterType((*Condition)(nil), "api.Condition")
	proto.RegisterType((*Sort)(nil), "api.Sort")
}

func init() { proto.RegisterFile("api/data.proto", fileDescriptor_51ac7b4dd81eed94) }

var fileDescriptor_51ac7b4dd81eed94 = []byte{
	// 496 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x53, 0xc1, 0x8e, 0xd3, 0x30,
	0x10, 0xc5, 0x4d, 0x42, 0x9b, 0xd9, 0x52, 0x55, 0x16, 0x42, 0x56, 0x05, 0xda, 0x2a, 0x5c, 0x0a,
	0x07, 0x83, 0x16, 0x09, 0x21, 0x8e, 0xbb, 0x4b, 0x25, 0xb4, 0x3d, 0x80, 0x03, 0x1f, 0xe0, 0x26,
	0x46, 0xb2, 0xda, 0xc4, 0x91, 0xe3, 0x22, 0x72, 0xe6, 0xc8, 0x37, 0xf1, 0x41, 0xfc, 0x05, 0xb2,
	0x1d, 0x77, 0x53, 0xd1, 0x1b, 0xb7, 0x99, 0xf7, 0xc6, 0x6f, 0xe6, 0x8d, 0x6d, 0x98, 0xf1, 0x46,
	0xbe, 0x2a, 0xb9, 0xe1, 0xb4, 0xd1, 0xca, 0x28, 0x1c, 0xf1, 0x46, 0x66, 0xbf, 0x10, 0xc4, 0x1b,
	0xb9, 0xef, 0xf0, 0x5b, 0x48, 0x2d, 0xb7, 0xe5, 0xad, 0x68, 0x09, 0x5a, 0x46, 0xab, 0x8b, 0x2b,
	0x42, 0x79, 0x23, 0xa9, 0x65, 0xe9, 0x6d, 0xa0, 0x3e, 0xd4, 0x46, 0x77, 0xec, 0xbe, 0x74, 0x71,
	0x07, 0xb3, 0x53, 0x12, 0xcf, 0x21, 0xda, 0x89, 0x8e, 0xa0, 0x25, 0x5a, 0xa5, 0xcc, 0x86, 0xf8,
	0x39, 0x24, 0xdf, 0xf9, 0xfe, 0x20, 0xc8, 0x68, 0x89, 0x56, 0x17, 0x57, 0x8f, 0x9c, 0x6e, 0x38,
	0xc5, 0x3c, 0xf7, 0x7e, 0xf4, 0x0e, 0x65, 0xbf, 0x11, 0x4c, 0x02, 0x8e, 0x67, 0x30, 0x92, 0x65,
	0x2f, 0x33, 0x92, 0x25, 0xc6, 0x10, 0xd7, 0xbc, 0xf2, 0x22, 0x29, 0x73, 0x31, 0x26, 0x30, 0x2e,
	0x54, 0x55, 0x89, 0xda, 0x90, 0xc8, 0xc1, 0x21, 0xc5, 0x14, 0x92, 0x6f, 0x4a, 0x57, 0x2d, 0x89,
	0x07, 0x5e, 0x82, 0x36, 0x5d, 0x5b, 0xca, 0x7b, 0xf1, 0x65, 0x8b, 0x1b, 0x80, 0x7b, 0xf0, 0x8c,
	0x87, 0xcb, 0x53, 0x0f, 0xa9, 0xd3, 0xb3, 0x27, 0x86, 0xf3, 0xff, 0x41, 0x10, 0x5b, 0xec, 0x3f,
	0x67, 0x7f, 0x01, 0x13, 0x3b, 0xd4, 0x97, 0xae, 0x11, 0x24, 0x5e, 0xa2, 0xd5, 0xac, 0x5f, 0xd9,
	0xba, 0x07, 0xd9, 0x91, 0xc6, 0xaf, 0x61, 0x2c, 0xeb, 0x52, 0xfc, 0x10, 0x2d, 0x49, 0x9c, 0xd1,
	0x27, 0xc7, 0x4a, 0xfa, 0xd1, 0x13, 0xde, 0x66, 0x28, 0x5b, 0xac, 0x61, 0x3a, 0x24, 0xce, 0x58,
	0x5d, 0x9e, 0x5a, 0x05, 0xa7, 0xe8, 0xce, 0x0c, 0xbd, 0x7e, 0x85, 0xc4, 0x61, 0xff, 0x78, 0x25,
	0x30, 0x6e, 0xb4, 0xac, 0xb8, 0xee, 0x9c, 0xc0, 0x84, 0x85, 0x14, 0x67, 0x30, 0xdd, 0x89, 0x2e,
	0x37, 0xfa, 0x50, 0x98, 0x83, 0x16, 0xbd, 0xed, 0x13, 0x2c, 0xfb, 0x89, 0x60, 0x92, 0x8b, 0xbd,
	0x28, 0x8c, 0xd2, 0x98, 0x02, 0x14, 0xaa, 0x2e, 0xa5, 0x91, 0xaa, 0x0e, 0xaf, 0x72, 0xe6, 0xc6,
	0xb9, 0x09, 0x30, 0x1b, 0x54, 0xd8, 0x35, 0xb7, 0x3b, 0xd9, 0xb8, 0xbe, 0x09, 0x73, 0x31, 0x7e,
	0x06, 0x71, 0xab, 0xb4, 0xdf, 0x71, 0xb8, 0xb7, 0x5c, 0x69, 0xc3, 0x1c, 0x8c, 0x1f, 0x43, 0xb2,
	0x91, 0x95, 0x34, 0x6e, 0xd1, 0x09, 0xf3, 0x49, 0x76, 0x07, 0xe9, 0xb1, 0x83, 0x2d, 0x69, 0xb8,
	0xe6, 0x55, 0xef, 0xd1, 0x27, 0xb6, 0x97, 0xed, 0x1c, 0xae, 0xd4, 0xc6, 0xb6, 0xd2, 0x6f, 0xce,
	0x36, 0x9b, 0xf6, 0xdb, 0xca, 0x28, 0xc4, 0x79, 0xdf, 0xea, 0x8c, 0xce, 0x1c, 0x22, 0xde, 0x16,
	0xfd, 0xaa, 0x6c, 0xf8, 0xf2, 0x29, 0x4c, 0xc2, 0x4d, 0xe3, 0x31, 0x44, 0xf9, 0xe7, 0xcd, 0xfc,
	0x81, 0x0d, 0x6e, 0x55, 0x31, 0x47, 0xd7, 0x97, 0x80, 0x8b, 0x9a, 0xf2, 0xad, 0xd0, 0xb2, 0xa0,
	0x7b, 0xfb, 0x39, 0x79, 0x23, 0xaf, 0x53, 0xfb, 0xb4, 0x3f, 0xd9, 0x7f, 0xbd, 0x7d, 0xe8, 0xbe,
	0xf7, 0x9b, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x50, 0x82, 0x96, 0x2d, 0xf0, 0x03, 0x00, 0x00,
}
