// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/rs.proto

package api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Code 响应结果码
type Code int32

const (
	// Success 成功
	Code_Success Code = 0
	// Fail 失败
	Code_Fail Code = 1
)

var Code_name = map[int32]string{
	0: "Success",
	1: "Fail",
}

var Code_value = map[string]int32{
	"Success": 0,
	"Fail":    1,
}

func (x Code) String() string {
	return proto.EnumName(Code_name, int32(x))
}

func (Code) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ae6ce81ad544face, []int{0}
}

// ReqConf 请求获取数据库引擎对象
type ReqConf struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqConf) Reset()         { *m = ReqConf{} }
func (m *ReqConf) String() string { return proto.CompactTextString(m) }
func (*ReqConf) ProtoMessage()    {}
func (*ReqConf) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae6ce81ad544face, []int{0}
}

func (m *ReqConf) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqConf.Unmarshal(m, b)
}
func (m *ReqConf) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqConf.Marshal(b, m, deterministic)
}
func (m *ReqConf) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqConf.Merge(m, src)
}
func (m *ReqConf) XXX_Size() int {
	return xxx_messageInfo_ReqConf.Size(m)
}
func (m *ReqConf) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqConf.DiscardUnknown(m)
}

var xxx_messageInfo_ReqConf proto.InternalMessageInfo

// RespConf 响应获取数据库引擎对象
type RespConf struct {
	// Code 响应结果码
	Code Code `protobuf:"varint,1,opt,name=Code,proto3,enum=api.Code" json:"Code,omitempty"`
	// Conf 数据库引擎对象
	Conf *Conf `protobuf:"bytes,2,opt,name=Conf,proto3" json:"Conf,omitempty"`
	// ErrMsg 错误信息
	ErrMsg               string   `protobuf:"bytes,3,opt,name=ErrMsg,proto3" json:"ErrMsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RespConf) Reset()         { *m = RespConf{} }
func (m *RespConf) String() string { return proto.CompactTextString(m) }
func (*RespConf) ProtoMessage()    {}
func (*RespConf) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae6ce81ad544face, []int{1}
}

func (m *RespConf) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RespConf.Unmarshal(m, b)
}
func (m *RespConf) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RespConf.Marshal(b, m, deterministic)
}
func (m *RespConf) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RespConf.Merge(m, src)
}
func (m *RespConf) XXX_Size() int {
	return xxx_messageInfo_RespConf.Size(m)
}
func (m *RespConf) XXX_DiscardUnknown() {
	xxx_messageInfo_RespConf.DiscardUnknown(m)
}

var xxx_messageInfo_RespConf proto.InternalMessageInfo

func (m *RespConf) GetCode() Code {
	if m != nil {
		return m.Code
	}
	return Code_Success
}

func (m *RespConf) GetConf() *Conf {
	if m != nil {
		return m.Conf
	}
	return nil
}

func (m *RespConf) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

// ReqDatabases 请求获取数据库集合
type ReqDatabases struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqDatabases) Reset()         { *m = ReqDatabases{} }
func (m *ReqDatabases) String() string { return proto.CompactTextString(m) }
func (*ReqDatabases) ProtoMessage()    {}
func (*ReqDatabases) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae6ce81ad544face, []int{2}
}

func (m *ReqDatabases) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqDatabases.Unmarshal(m, b)
}
func (m *ReqDatabases) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqDatabases.Marshal(b, m, deterministic)
}
func (m *ReqDatabases) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqDatabases.Merge(m, src)
}
func (m *ReqDatabases) XXX_Size() int {
	return xxx_messageInfo_ReqDatabases.Size(m)
}
func (m *ReqDatabases) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqDatabases.DiscardUnknown(m)
}

var xxx_messageInfo_ReqDatabases proto.InternalMessageInfo

// RespDatabases 响应获取数据库集合
type RespDatabases struct {
	// Code 响应结果码
	Code Code `protobuf:"varint,1,opt,name=Code,proto3,enum=api.Code" json:"Code,omitempty"`
	// Databases 数据库对象集合
	Databases []*Database `protobuf:"bytes,2,rep,name=Databases,proto3" json:"Databases,omitempty"`
	// ErrMsg 错误信息
	ErrMsg               string   `protobuf:"bytes,3,opt,name=ErrMsg,proto3" json:"ErrMsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RespDatabases) Reset()         { *m = RespDatabases{} }
func (m *RespDatabases) String() string { return proto.CompactTextString(m) }
func (*RespDatabases) ProtoMessage()    {}
func (*RespDatabases) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae6ce81ad544face, []int{3}
}

func (m *RespDatabases) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RespDatabases.Unmarshal(m, b)
}
func (m *RespDatabases) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RespDatabases.Marshal(b, m, deterministic)
}
func (m *RespDatabases) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RespDatabases.Merge(m, src)
}
func (m *RespDatabases) XXX_Size() int {
	return xxx_messageInfo_RespDatabases.Size(m)
}
func (m *RespDatabases) XXX_DiscardUnknown() {
	xxx_messageInfo_RespDatabases.DiscardUnknown(m)
}

var xxx_messageInfo_RespDatabases proto.InternalMessageInfo

func (m *RespDatabases) GetCode() Code {
	if m != nil {
		return m.Code
	}
	return Code_Success
}

func (m *RespDatabases) GetDatabases() []*Database {
	if m != nil {
		return m.Databases
	}
	return nil
}

func (m *RespDatabases) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

// ReqForms 请求获取数据库表集合
type ReqForms struct {
	// DatabaseName 数据库名称
	DatabaseName         string   `protobuf:"bytes,1,opt,name=DatabaseName,proto3" json:"DatabaseName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqForms) Reset()         { *m = ReqForms{} }
func (m *ReqForms) String() string { return proto.CompactTextString(m) }
func (*ReqForms) ProtoMessage()    {}
func (*ReqForms) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae6ce81ad544face, []int{4}
}

func (m *ReqForms) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqForms.Unmarshal(m, b)
}
func (m *ReqForms) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqForms.Marshal(b, m, deterministic)
}
func (m *ReqForms) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqForms.Merge(m, src)
}
func (m *ReqForms) XXX_Size() int {
	return xxx_messageInfo_ReqForms.Size(m)
}
func (m *ReqForms) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqForms.DiscardUnknown(m)
}

var xxx_messageInfo_ReqForms proto.InternalMessageInfo

func (m *ReqForms) GetDatabaseName() string {
	if m != nil {
		return m.DatabaseName
	}
	return ""
}

// RespForms 响应获取数据库表集合
type RespForms struct {
	// Code 响应结果码
	Code Code `protobuf:"varint,1,opt,name=Code,proto3,enum=api.Code" json:"Code,omitempty"`
	// Forms 数据库表对象集合
	Forms []*Form `protobuf:"bytes,2,rep,name=Forms,proto3" json:"Forms,omitempty"`
	// ErrMsg 错误信息
	ErrMsg               string   `protobuf:"bytes,3,opt,name=ErrMsg,proto3" json:"ErrMsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RespForms) Reset()         { *m = RespForms{} }
func (m *RespForms) String() string { return proto.CompactTextString(m) }
func (*RespForms) ProtoMessage()    {}
func (*RespForms) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae6ce81ad544face, []int{5}
}

func (m *RespForms) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RespForms.Unmarshal(m, b)
}
func (m *RespForms) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RespForms.Marshal(b, m, deterministic)
}
func (m *RespForms) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RespForms.Merge(m, src)
}
func (m *RespForms) XXX_Size() int {
	return xxx_messageInfo_RespForms.Size(m)
}
func (m *RespForms) XXX_DiscardUnknown() {
	xxx_messageInfo_RespForms.DiscardUnknown(m)
}

var xxx_messageInfo_RespForms proto.InternalMessageInfo

func (m *RespForms) GetCode() Code {
	if m != nil {
		return m.Code
	}
	return Code_Success
}

func (m *RespForms) GetForms() []*Form {
	if m != nil {
		return m.Forms
	}
	return nil
}

func (m *RespForms) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

// ReqCreateDatabase 请求新建数据库
type ReqCreateDatabase struct {
	// Name 数据库名称，根据需求可以随时变化
	Name string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	// Comment 数据库描述
	Comment              string   `protobuf:"bytes,2,opt,name=Comment,proto3" json:"Comment,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqCreateDatabase) Reset()         { *m = ReqCreateDatabase{} }
func (m *ReqCreateDatabase) String() string { return proto.CompactTextString(m) }
func (*ReqCreateDatabase) ProtoMessage()    {}
func (*ReqCreateDatabase) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae6ce81ad544face, []int{6}
}

func (m *ReqCreateDatabase) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqCreateDatabase.Unmarshal(m, b)
}
func (m *ReqCreateDatabase) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqCreateDatabase.Marshal(b, m, deterministic)
}
func (m *ReqCreateDatabase) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqCreateDatabase.Merge(m, src)
}
func (m *ReqCreateDatabase) XXX_Size() int {
	return xxx_messageInfo_ReqCreateDatabase.Size(m)
}
func (m *ReqCreateDatabase) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqCreateDatabase.DiscardUnknown(m)
}

var xxx_messageInfo_ReqCreateDatabase proto.InternalMessageInfo

func (m *ReqCreateDatabase) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ReqCreateDatabase) GetComment() string {
	if m != nil {
		return m.Comment
	}
	return ""
}

// RespDatabase 响应新建数据库
type RespDatabase struct {
	// Code 响应结果码
	Code Code `protobuf:"varint,1,opt,name=Code,proto3,enum=api.Code" json:"Code,omitempty"`
	// database 数据库对象
	Database *Database `protobuf:"bytes,2,opt,name=Database,proto3" json:"Database,omitempty"`
	// ErrMsg 错误信息
	ErrMsg               string   `protobuf:"bytes,3,opt,name=ErrMsg,proto3" json:"ErrMsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RespDatabase) Reset()         { *m = RespDatabase{} }
func (m *RespDatabase) String() string { return proto.CompactTextString(m) }
func (*RespDatabase) ProtoMessage()    {}
func (*RespDatabase) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae6ce81ad544face, []int{7}
}

func (m *RespDatabase) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RespDatabase.Unmarshal(m, b)
}
func (m *RespDatabase) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RespDatabase.Marshal(b, m, deterministic)
}
func (m *RespDatabase) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RespDatabase.Merge(m, src)
}
func (m *RespDatabase) XXX_Size() int {
	return xxx_messageInfo_RespDatabase.Size(m)
}
func (m *RespDatabase) XXX_DiscardUnknown() {
	xxx_messageInfo_RespDatabase.DiscardUnknown(m)
}

var xxx_messageInfo_RespDatabase proto.InternalMessageInfo

func (m *RespDatabase) GetCode() Code {
	if m != nil {
		return m.Code
	}
	return Code_Success
}

func (m *RespDatabase) GetDatabase() *Database {
	if m != nil {
		return m.Database
	}
	return nil
}

func (m *RespDatabase) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

// ReqCreateForm 请求创建表
type ReqCreateForm struct {
	// DatabaseName 数据库名称
	DatabaseName string `protobuf:"bytes,1,opt,name=DatabaseName,proto3" json:"DatabaseName,omitempty"`
	// Name 表名称
	Name string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	// Comment 表描述
	Comment string `protobuf:"bytes,3,opt,name=Comment,proto3" json:"Comment,omitempty"`
	// FormType 表类型
	FormType             FormType `protobuf:"varint,4,opt,name=FormType,proto3,enum=api.FormType" json:"FormType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqCreateForm) Reset()         { *m = ReqCreateForm{} }
func (m *ReqCreateForm) String() string { return proto.CompactTextString(m) }
func (*ReqCreateForm) ProtoMessage()    {}
func (*ReqCreateForm) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae6ce81ad544face, []int{8}
}

func (m *ReqCreateForm) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqCreateForm.Unmarshal(m, b)
}
func (m *ReqCreateForm) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqCreateForm.Marshal(b, m, deterministic)
}
func (m *ReqCreateForm) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqCreateForm.Merge(m, src)
}
func (m *ReqCreateForm) XXX_Size() int {
	return xxx_messageInfo_ReqCreateForm.Size(m)
}
func (m *ReqCreateForm) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqCreateForm.DiscardUnknown(m)
}

var xxx_messageInfo_ReqCreateForm proto.InternalMessageInfo

func (m *ReqCreateForm) GetDatabaseName() string {
	if m != nil {
		return m.DatabaseName
	}
	return ""
}

func (m *ReqCreateForm) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ReqCreateForm) GetComment() string {
	if m != nil {
		return m.Comment
	}
	return ""
}

func (m *ReqCreateForm) GetFormType() FormType {
	if m != nil {
		return m.FormType
	}
	return FormType_SQL
}

// ReqKey 请求新建主键
type ReqCreateKey struct {
	// DatabaseName 数据库名称
	DatabaseName string `protobuf:"bytes,1,opt,name=DatabaseName,proto3" json:"DatabaseName,omitempty"`
	// FormName 表名称
	FormName string `protobuf:"bytes,2,opt,name=FormName,proto3" json:"FormName,omitempty"`
	// Comment 主键结构名，按照规范结构组成的主键字段名称，由对象结构层级字段通过'.'组成，如'i','in.s'
	KeyStructure         string   `protobuf:"bytes,3,opt,name=KeyStructure,proto3" json:"KeyStructure,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqCreateKey) Reset()         { *m = ReqCreateKey{} }
func (m *ReqCreateKey) String() string { return proto.CompactTextString(m) }
func (*ReqCreateKey) ProtoMessage()    {}
func (*ReqCreateKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae6ce81ad544face, []int{9}
}

func (m *ReqCreateKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqCreateKey.Unmarshal(m, b)
}
func (m *ReqCreateKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqCreateKey.Marshal(b, m, deterministic)
}
func (m *ReqCreateKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqCreateKey.Merge(m, src)
}
func (m *ReqCreateKey) XXX_Size() int {
	return xxx_messageInfo_ReqCreateKey.Size(m)
}
func (m *ReqCreateKey) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqCreateKey.DiscardUnknown(m)
}

var xxx_messageInfo_ReqCreateKey proto.InternalMessageInfo

func (m *ReqCreateKey) GetDatabaseName() string {
	if m != nil {
		return m.DatabaseName
	}
	return ""
}

func (m *ReqCreateKey) GetFormName() string {
	if m != nil {
		return m.FormName
	}
	return ""
}

func (m *ReqCreateKey) GetKeyStructure() string {
	if m != nil {
		return m.KeyStructure
	}
	return ""
}

// ReqIndex 请求新建索引
type ReqCreateIndex struct {
	// DatabaseName 数据库名称
	DatabaseName string `protobuf:"bytes,1,opt,name=DatabaseName,proto3" json:"DatabaseName,omitempty"`
	// FormName 表名称
	FormName string `protobuf:"bytes,2,opt,name=FormName,proto3" json:"FormName,omitempty"`
	// Comment 主键结构名，按照规范结构组成的主键字段名称，由对象结构层级字段通过'.'组成，如'i','in.s'
	KeyStructure         string   `protobuf:"bytes,3,opt,name=KeyStructure,proto3" json:"KeyStructure,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqCreateIndex) Reset()         { *m = ReqCreateIndex{} }
func (m *ReqCreateIndex) String() string { return proto.CompactTextString(m) }
func (*ReqCreateIndex) ProtoMessage()    {}
func (*ReqCreateIndex) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae6ce81ad544face, []int{10}
}

func (m *ReqCreateIndex) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqCreateIndex.Unmarshal(m, b)
}
func (m *ReqCreateIndex) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqCreateIndex.Marshal(b, m, deterministic)
}
func (m *ReqCreateIndex) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqCreateIndex.Merge(m, src)
}
func (m *ReqCreateIndex) XXX_Size() int {
	return xxx_messageInfo_ReqCreateIndex.Size(m)
}
func (m *ReqCreateIndex) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqCreateIndex.DiscardUnknown(m)
}

var xxx_messageInfo_ReqCreateIndex proto.InternalMessageInfo

func (m *ReqCreateIndex) GetDatabaseName() string {
	if m != nil {
		return m.DatabaseName
	}
	return ""
}

func (m *ReqCreateIndex) GetFormName() string {
	if m != nil {
		return m.FormName
	}
	return ""
}

func (m *ReqCreateIndex) GetKeyStructure() string {
	if m != nil {
		return m.KeyStructure
	}
	return ""
}

// ReqPutD 新增数据
type ReqPutD struct {
	// Key 数据库名称
	Key string `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	// Value 插入数据对象
	Value                []byte   `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqPutD) Reset()         { *m = ReqPutD{} }
func (m *ReqPutD) String() string { return proto.CompactTextString(m) }
func (*ReqPutD) ProtoMessage()    {}
func (*ReqPutD) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae6ce81ad544face, []int{11}
}

func (m *ReqPutD) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqPutD.Unmarshal(m, b)
}
func (m *ReqPutD) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqPutD.Marshal(b, m, deterministic)
}
func (m *ReqPutD) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqPutD.Merge(m, src)
}
func (m *ReqPutD) XXX_Size() int {
	return xxx_messageInfo_ReqPutD.Size(m)
}
func (m *ReqPutD) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqPutD.DiscardUnknown(m)
}

var xxx_messageInfo_ReqPutD proto.InternalMessageInfo

func (m *ReqPutD) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *ReqPutD) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

// RespPutD 响应新增数据
type RespPutD struct {
	// Code 响应结果码
	Code Code `protobuf:"varint,1,opt,name=Code,proto3,enum=api.Code" json:"Code,omitempty"`
	// HashKey HashKey
	HashKey uint64 `protobuf:"varint,2,opt,name=HashKey,proto3" json:"HashKey,omitempty"`
	// ErrMsg 错误信息
	ErrMsg               string   `protobuf:"bytes,3,opt,name=ErrMsg,proto3" json:"ErrMsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RespPutD) Reset()         { *m = RespPutD{} }
func (m *RespPutD) String() string { return proto.CompactTextString(m) }
func (*RespPutD) ProtoMessage()    {}
func (*RespPutD) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae6ce81ad544face, []int{12}
}

func (m *RespPutD) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RespPutD.Unmarshal(m, b)
}
func (m *RespPutD) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RespPutD.Marshal(b, m, deterministic)
}
func (m *RespPutD) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RespPutD.Merge(m, src)
}
func (m *RespPutD) XXX_Size() int {
	return xxx_messageInfo_RespPutD.Size(m)
}
func (m *RespPutD) XXX_DiscardUnknown() {
	xxx_messageInfo_RespPutD.DiscardUnknown(m)
}

var xxx_messageInfo_RespPutD proto.InternalMessageInfo

func (m *RespPutD) GetCode() Code {
	if m != nil {
		return m.Code
	}
	return Code_Success
}

func (m *RespPutD) GetHashKey() uint64 {
	if m != nil {
		return m.HashKey
	}
	return 0
}

func (m *RespPutD) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

// ReqSetD 新增数据
type ReqSetD struct {
	// Key 数据库名称
	Key string `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	// Value 插入数据对象
	Value                []byte   `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqSetD) Reset()         { *m = ReqSetD{} }
func (m *ReqSetD) String() string { return proto.CompactTextString(m) }
func (*ReqSetD) ProtoMessage()    {}
func (*ReqSetD) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae6ce81ad544face, []int{13}
}

func (m *ReqSetD) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqSetD.Unmarshal(m, b)
}
func (m *ReqSetD) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqSetD.Marshal(b, m, deterministic)
}
func (m *ReqSetD) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqSetD.Merge(m, src)
}
func (m *ReqSetD) XXX_Size() int {
	return xxx_messageInfo_ReqSetD.Size(m)
}
func (m *ReqSetD) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqSetD.DiscardUnknown(m)
}

var xxx_messageInfo_ReqSetD proto.InternalMessageInfo

func (m *ReqSetD) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *ReqSetD) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

// RespSetD 响应新增数据
type RespSetD struct {
	// Code 响应结果码
	Code Code `protobuf:"varint,1,opt,name=Code,proto3,enum=api.Code" json:"Code,omitempty"`
	// HashKey HashKey
	HashKey uint64 `protobuf:"varint,2,opt,name=HashKey,proto3" json:"HashKey,omitempty"`
	// ErrMsg 错误信息
	ErrMsg               string   `protobuf:"bytes,3,opt,name=ErrMsg,proto3" json:"ErrMsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RespSetD) Reset()         { *m = RespSetD{} }
func (m *RespSetD) String() string { return proto.CompactTextString(m) }
func (*RespSetD) ProtoMessage()    {}
func (*RespSetD) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae6ce81ad544face, []int{14}
}

func (m *RespSetD) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RespSetD.Unmarshal(m, b)
}
func (m *RespSetD) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RespSetD.Marshal(b, m, deterministic)
}
func (m *RespSetD) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RespSetD.Merge(m, src)
}
func (m *RespSetD) XXX_Size() int {
	return xxx_messageInfo_RespSetD.Size(m)
}
func (m *RespSetD) XXX_DiscardUnknown() {
	xxx_messageInfo_RespSetD.DiscardUnknown(m)
}

var xxx_messageInfo_RespSetD proto.InternalMessageInfo

func (m *RespSetD) GetCode() Code {
	if m != nil {
		return m.Code
	}
	return Code_Success
}

func (m *RespSetD) GetHashKey() uint64 {
	if m != nil {
		return m.HashKey
	}
	return 0
}

func (m *RespSetD) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

// ReqGetD 获取数据
type ReqGetD struct {
	// Key 数据库名称
	Key                  string   `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqGetD) Reset()         { *m = ReqGetD{} }
func (m *ReqGetD) String() string { return proto.CompactTextString(m) }
func (*ReqGetD) ProtoMessage()    {}
func (*ReqGetD) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae6ce81ad544face, []int{15}
}

func (m *ReqGetD) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqGetD.Unmarshal(m, b)
}
func (m *ReqGetD) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqGetD.Marshal(b, m, deterministic)
}
func (m *ReqGetD) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqGetD.Merge(m, src)
}
func (m *ReqGetD) XXX_Size() int {
	return xxx_messageInfo_ReqGetD.Size(m)
}
func (m *ReqGetD) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqGetD.DiscardUnknown(m)
}

var xxx_messageInfo_ReqGetD proto.InternalMessageInfo

func (m *ReqGetD) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

// RespGetD 响应获取数据
type RespGetD struct {
	// Code 响应结果码
	Code Code `protobuf:"varint,1,opt,name=Code,proto3,enum=api.Code" json:"Code,omitempty"`
	// Value Value
	Value []byte `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"`
	// ErrMsg 错误信息
	ErrMsg               string   `protobuf:"bytes,3,opt,name=ErrMsg,proto3" json:"ErrMsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RespGetD) Reset()         { *m = RespGetD{} }
func (m *RespGetD) String() string { return proto.CompactTextString(m) }
func (*RespGetD) ProtoMessage()    {}
func (*RespGetD) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae6ce81ad544face, []int{16}
}

func (m *RespGetD) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RespGetD.Unmarshal(m, b)
}
func (m *RespGetD) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RespGetD.Marshal(b, m, deterministic)
}
func (m *RespGetD) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RespGetD.Merge(m, src)
}
func (m *RespGetD) XXX_Size() int {
	return xxx_messageInfo_RespGetD.Size(m)
}
func (m *RespGetD) XXX_DiscardUnknown() {
	xxx_messageInfo_RespGetD.DiscardUnknown(m)
}

var xxx_messageInfo_RespGetD proto.InternalMessageInfo

func (m *RespGetD) GetCode() Code {
	if m != nil {
		return m.Code
	}
	return Code_Success
}

func (m *RespGetD) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *RespGetD) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

// ReqPut 新增数据
type ReqPut struct {
	// DatabaseName 数据库名称
	DatabaseName string `protobuf:"bytes,1,opt,name=DatabaseName,proto3" json:"DatabaseName,omitempty"`
	// FormName 表名称
	FormName string `protobuf:"bytes,2,opt,name=FormName,proto3" json:"FormName,omitempty"`
	// Key 数据库名称
	Key string `protobuf:"bytes,3,opt,name=Key,proto3" json:"Key,omitempty"`
	// Value 插入数据对象
	Value                []byte   `protobuf:"bytes,4,opt,name=Value,proto3" json:"Value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqPut) Reset()         { *m = ReqPut{} }
func (m *ReqPut) String() string { return proto.CompactTextString(m) }
func (*ReqPut) ProtoMessage()    {}
func (*ReqPut) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae6ce81ad544face, []int{17}
}

func (m *ReqPut) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqPut.Unmarshal(m, b)
}
func (m *ReqPut) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqPut.Marshal(b, m, deterministic)
}
func (m *ReqPut) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqPut.Merge(m, src)
}
func (m *ReqPut) XXX_Size() int {
	return xxx_messageInfo_ReqPut.Size(m)
}
func (m *ReqPut) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqPut.DiscardUnknown(m)
}

var xxx_messageInfo_ReqPut proto.InternalMessageInfo

func (m *ReqPut) GetDatabaseName() string {
	if m != nil {
		return m.DatabaseName
	}
	return ""
}

func (m *ReqPut) GetFormName() string {
	if m != nil {
		return m.FormName
	}
	return ""
}

func (m *ReqPut) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *ReqPut) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

// RespPut 响应新增数据
type RespPut struct {
	// Code 响应结果码
	Code Code `protobuf:"varint,1,opt,name=Code,proto3,enum=api.Code" json:"Code,omitempty"`
	// HashKey HashKey
	HashKey uint64 `protobuf:"varint,2,opt,name=HashKey,proto3" json:"HashKey,omitempty"`
	// ErrMsg 错误信息
	ErrMsg               string   `protobuf:"bytes,3,opt,name=ErrMsg,proto3" json:"ErrMsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RespPut) Reset()         { *m = RespPut{} }
func (m *RespPut) String() string { return proto.CompactTextString(m) }
func (*RespPut) ProtoMessage()    {}
func (*RespPut) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae6ce81ad544face, []int{18}
}

func (m *RespPut) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RespPut.Unmarshal(m, b)
}
func (m *RespPut) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RespPut.Marshal(b, m, deterministic)
}
func (m *RespPut) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RespPut.Merge(m, src)
}
func (m *RespPut) XXX_Size() int {
	return xxx_messageInfo_RespPut.Size(m)
}
func (m *RespPut) XXX_DiscardUnknown() {
	xxx_messageInfo_RespPut.DiscardUnknown(m)
}

var xxx_messageInfo_RespPut proto.InternalMessageInfo

func (m *RespPut) GetCode() Code {
	if m != nil {
		return m.Code
	}
	return Code_Success
}

func (m *RespPut) GetHashKey() uint64 {
	if m != nil {
		return m.HashKey
	}
	return 0
}

func (m *RespPut) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

// ReqSet 新增数据
type ReqSet struct {
	// DatabaseName 数据库名称
	DatabaseName string `protobuf:"bytes,1,opt,name=DatabaseName,proto3" json:"DatabaseName,omitempty"`
	// FormName 表名称
	FormName string `protobuf:"bytes,2,opt,name=FormName,proto3" json:"FormName,omitempty"`
	// Key 数据库名称
	Key string `protobuf:"bytes,3,opt,name=Key,proto3" json:"Key,omitempty"`
	// Value 插入数据对象
	Value                []byte   `protobuf:"bytes,4,opt,name=Value,proto3" json:"Value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqSet) Reset()         { *m = ReqSet{} }
func (m *ReqSet) String() string { return proto.CompactTextString(m) }
func (*ReqSet) ProtoMessage()    {}
func (*ReqSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae6ce81ad544face, []int{19}
}

func (m *ReqSet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqSet.Unmarshal(m, b)
}
func (m *ReqSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqSet.Marshal(b, m, deterministic)
}
func (m *ReqSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqSet.Merge(m, src)
}
func (m *ReqSet) XXX_Size() int {
	return xxx_messageInfo_ReqSet.Size(m)
}
func (m *ReqSet) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqSet.DiscardUnknown(m)
}

var xxx_messageInfo_ReqSet proto.InternalMessageInfo

func (m *ReqSet) GetDatabaseName() string {
	if m != nil {
		return m.DatabaseName
	}
	return ""
}

func (m *ReqSet) GetFormName() string {
	if m != nil {
		return m.FormName
	}
	return ""
}

func (m *ReqSet) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *ReqSet) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

// RespSet 响应新增数据
type RespSet struct {
	// Code 响应结果码
	Code Code `protobuf:"varint,1,opt,name=Code,proto3,enum=api.Code" json:"Code,omitempty"`
	// HashKey HashKey
	HashKey uint64 `protobuf:"varint,2,opt,name=HashKey,proto3" json:"HashKey,omitempty"`
	// ErrMsg 错误信息
	ErrMsg               string   `protobuf:"bytes,3,opt,name=ErrMsg,proto3" json:"ErrMsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RespSet) Reset()         { *m = RespSet{} }
func (m *RespSet) String() string { return proto.CompactTextString(m) }
func (*RespSet) ProtoMessage()    {}
func (*RespSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae6ce81ad544face, []int{20}
}

func (m *RespSet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RespSet.Unmarshal(m, b)
}
func (m *RespSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RespSet.Marshal(b, m, deterministic)
}
func (m *RespSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RespSet.Merge(m, src)
}
func (m *RespSet) XXX_Size() int {
	return xxx_messageInfo_RespSet.Size(m)
}
func (m *RespSet) XXX_DiscardUnknown() {
	xxx_messageInfo_RespSet.DiscardUnknown(m)
}

var xxx_messageInfo_RespSet proto.InternalMessageInfo

func (m *RespSet) GetCode() Code {
	if m != nil {
		return m.Code
	}
	return Code_Success
}

func (m *RespSet) GetHashKey() uint64 {
	if m != nil {
		return m.HashKey
	}
	return 0
}

func (m *RespSet) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

// ReqGet 获取数据
type ReqGet struct {
	// DatabaseName 数据库名称
	DatabaseName string `protobuf:"bytes,1,opt,name=DatabaseName,proto3" json:"DatabaseName,omitempty"`
	// FormName 表名称
	FormName string `protobuf:"bytes,2,opt,name=FormName,proto3" json:"FormName,omitempty"`
	// Key 数据库名称
	Key                  string   `protobuf:"bytes,3,opt,name=Key,proto3" json:"Key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqGet) Reset()         { *m = ReqGet{} }
func (m *ReqGet) String() string { return proto.CompactTextString(m) }
func (*ReqGet) ProtoMessage()    {}
func (*ReqGet) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae6ce81ad544face, []int{21}
}

func (m *ReqGet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqGet.Unmarshal(m, b)
}
func (m *ReqGet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqGet.Marshal(b, m, deterministic)
}
func (m *ReqGet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqGet.Merge(m, src)
}
func (m *ReqGet) XXX_Size() int {
	return xxx_messageInfo_ReqGet.Size(m)
}
func (m *ReqGet) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqGet.DiscardUnknown(m)
}

var xxx_messageInfo_ReqGet proto.InternalMessageInfo

func (m *ReqGet) GetDatabaseName() string {
	if m != nil {
		return m.DatabaseName
	}
	return ""
}

func (m *ReqGet) GetFormName() string {
	if m != nil {
		return m.FormName
	}
	return ""
}

func (m *ReqGet) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

// RespGet 响应获取数据
type RespGet struct {
	// Code 响应结果码
	Code Code `protobuf:"varint,1,opt,name=Code,proto3,enum=api.Code" json:"Code,omitempty"`
	// Value Value
	Value []byte `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"`
	// ErrMsg 错误信息
	ErrMsg               string   `protobuf:"bytes,3,opt,name=ErrMsg,proto3" json:"ErrMsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RespGet) Reset()         { *m = RespGet{} }
func (m *RespGet) String() string { return proto.CompactTextString(m) }
func (*RespGet) ProtoMessage()    {}
func (*RespGet) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae6ce81ad544face, []int{22}
}

func (m *RespGet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RespGet.Unmarshal(m, b)
}
func (m *RespGet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RespGet.Marshal(b, m, deterministic)
}
func (m *RespGet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RespGet.Merge(m, src)
}
func (m *RespGet) XXX_Size() int {
	return xxx_messageInfo_RespGet.Size(m)
}
func (m *RespGet) XXX_DiscardUnknown() {
	xxx_messageInfo_RespGet.DiscardUnknown(m)
}

var xxx_messageInfo_RespGet proto.InternalMessageInfo

func (m *RespGet) GetCode() Code {
	if m != nil {
		return m.Code
	}
	return Code_Success
}

func (m *RespGet) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *RespGet) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

// ReqSelect 获取数据
type ReqSelect struct {
	// DatabaseName 数据库名称
	DatabaseName string `protobuf:"bytes,1,opt,name=DatabaseName,proto3" json:"DatabaseName,omitempty"`
	// FormName 表名称
	FormName string `protobuf:"bytes,2,opt,name=FormName,proto3" json:"FormName,omitempty"`
	// selector 条件选择器
	Selector             *Selector `protobuf:"bytes,3,opt,name=Selector,proto3" json:"Selector,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ReqSelect) Reset()         { *m = ReqSelect{} }
func (m *ReqSelect) String() string { return proto.CompactTextString(m) }
func (*ReqSelect) ProtoMessage()    {}
func (*ReqSelect) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae6ce81ad544face, []int{23}
}

func (m *ReqSelect) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqSelect.Unmarshal(m, b)
}
func (m *ReqSelect) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqSelect.Marshal(b, m, deterministic)
}
func (m *ReqSelect) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqSelect.Merge(m, src)
}
func (m *ReqSelect) XXX_Size() int {
	return xxx_messageInfo_ReqSelect.Size(m)
}
func (m *ReqSelect) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqSelect.DiscardUnknown(m)
}

var xxx_messageInfo_ReqSelect proto.InternalMessageInfo

func (m *ReqSelect) GetDatabaseName() string {
	if m != nil {
		return m.DatabaseName
	}
	return ""
}

func (m *ReqSelect) GetFormName() string {
	if m != nil {
		return m.FormName
	}
	return ""
}

func (m *ReqSelect) GetSelector() *Selector {
	if m != nil {
		return m.Selector
	}
	return nil
}

// RespSelect 响应获取数据
type RespSelect struct {
	// Code 响应结果码
	Code Code `protobuf:"varint,1,opt,name=Code,proto3,enum=api.Code" json:"Code,omitempty"`
	// Count 获取数据总条数
	Count int32 `protobuf:"varint,2,opt,name=Count,proto3" json:"Count,omitempty"`
	// Value 获取数据结果
	Value []byte `protobuf:"bytes,3,opt,name=Value,proto3" json:"Value,omitempty"`
	// ErrMsg 错误信息
	ErrMsg               string   `protobuf:"bytes,4,opt,name=ErrMsg,proto3" json:"ErrMsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RespSelect) Reset()         { *m = RespSelect{} }
func (m *RespSelect) String() string { return proto.CompactTextString(m) }
func (*RespSelect) ProtoMessage()    {}
func (*RespSelect) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae6ce81ad544face, []int{24}
}

func (m *RespSelect) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RespSelect.Unmarshal(m, b)
}
func (m *RespSelect) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RespSelect.Marshal(b, m, deterministic)
}
func (m *RespSelect) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RespSelect.Merge(m, src)
}
func (m *RespSelect) XXX_Size() int {
	return xxx_messageInfo_RespSelect.Size(m)
}
func (m *RespSelect) XXX_DiscardUnknown() {
	xxx_messageInfo_RespSelect.DiscardUnknown(m)
}

var xxx_messageInfo_RespSelect proto.InternalMessageInfo

func (m *RespSelect) GetCode() Code {
	if m != nil {
		return m.Code
	}
	return Code_Success
}

func (m *RespSelect) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *RespSelect) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *RespSelect) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

// ReqGet 删除数据
type ReqRemove struct {
	// DatabaseName 数据库名称
	DatabaseName string `protobuf:"bytes,1,opt,name=DatabaseName,proto3" json:"DatabaseName,omitempty"`
	// FormName 表名称
	FormName string `protobuf:"bytes,2,opt,name=FormName,proto3" json:"FormName,omitempty"`
	// Key 数据库名称
	Key                  string   `protobuf:"bytes,3,opt,name=Key,proto3" json:"Key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqRemove) Reset()         { *m = ReqRemove{} }
func (m *ReqRemove) String() string { return proto.CompactTextString(m) }
func (*ReqRemove) ProtoMessage()    {}
func (*ReqRemove) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae6ce81ad544face, []int{25}
}

func (m *ReqRemove) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqRemove.Unmarshal(m, b)
}
func (m *ReqRemove) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqRemove.Marshal(b, m, deterministic)
}
func (m *ReqRemove) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqRemove.Merge(m, src)
}
func (m *ReqRemove) XXX_Size() int {
	return xxx_messageInfo_ReqRemove.Size(m)
}
func (m *ReqRemove) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqRemove.DiscardUnknown(m)
}

var xxx_messageInfo_ReqRemove proto.InternalMessageInfo

func (m *ReqRemove) GetDatabaseName() string {
	if m != nil {
		return m.DatabaseName
	}
	return ""
}

func (m *ReqRemove) GetFormName() string {
	if m != nil {
		return m.FormName
	}
	return ""
}

func (m *ReqRemove) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

// ReqDelete 删除数据
type ReqDelete struct {
	// DatabaseName 数据库名称
	DatabaseName string `protobuf:"bytes,1,opt,name=DatabaseName,proto3" json:"DatabaseName,omitempty"`
	// FormName 表名称
	FormName string `protobuf:"bytes,2,opt,name=FormName,proto3" json:"FormName,omitempty"`
	// selector 条件选择器
	Selector             *Selector `protobuf:"bytes,3,opt,name=Selector,proto3" json:"Selector,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ReqDelete) Reset()         { *m = ReqDelete{} }
func (m *ReqDelete) String() string { return proto.CompactTextString(m) }
func (*ReqDelete) ProtoMessage()    {}
func (*ReqDelete) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae6ce81ad544face, []int{26}
}

func (m *ReqDelete) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqDelete.Unmarshal(m, b)
}
func (m *ReqDelete) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqDelete.Marshal(b, m, deterministic)
}
func (m *ReqDelete) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqDelete.Merge(m, src)
}
func (m *ReqDelete) XXX_Size() int {
	return xxx_messageInfo_ReqDelete.Size(m)
}
func (m *ReqDelete) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqDelete.DiscardUnknown(m)
}

var xxx_messageInfo_ReqDelete proto.InternalMessageInfo

func (m *ReqDelete) GetDatabaseName() string {
	if m != nil {
		return m.DatabaseName
	}
	return ""
}

func (m *ReqDelete) GetFormName() string {
	if m != nil {
		return m.FormName
	}
	return ""
}

func (m *ReqDelete) GetSelector() *Selector {
	if m != nil {
		return m.Selector
	}
	return nil
}

// RespDelete 响应删除数据
type RespDelete struct {
	// Code 响应结果码
	Code Code `protobuf:"varint,1,opt,name=Code,proto3,enum=api.Code" json:"Code,omitempty"`
	// Count 获取数据总条数
	Count int32 `protobuf:"varint,2,opt,name=Count,proto3" json:"Count,omitempty"`
	// ErrMsg 错误信息
	ErrMsg               string   `protobuf:"bytes,3,opt,name=ErrMsg,proto3" json:"ErrMsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RespDelete) Reset()         { *m = RespDelete{} }
func (m *RespDelete) String() string { return proto.CompactTextString(m) }
func (*RespDelete) ProtoMessage()    {}
func (*RespDelete) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae6ce81ad544face, []int{27}
}

func (m *RespDelete) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RespDelete.Unmarshal(m, b)
}
func (m *RespDelete) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RespDelete.Marshal(b, m, deterministic)
}
func (m *RespDelete) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RespDelete.Merge(m, src)
}
func (m *RespDelete) XXX_Size() int {
	return xxx_messageInfo_RespDelete.Size(m)
}
func (m *RespDelete) XXX_DiscardUnknown() {
	xxx_messageInfo_RespDelete.DiscardUnknown(m)
}

var xxx_messageInfo_RespDelete proto.InternalMessageInfo

func (m *RespDelete) GetCode() Code {
	if m != nil {
		return m.Code
	}
	return Code_Success
}

func (m *RespDelete) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *RespDelete) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

// Resp 通用响应对象
type Resp struct {
	// Code 响应结果码
	Code Code `protobuf:"varint,1,opt,name=Code,proto3,enum=api.Code" json:"Code,omitempty"`
	// ErrMsg 错误信息
	ErrMsg               string   `protobuf:"bytes,2,opt,name=ErrMsg,proto3" json:"ErrMsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Resp) Reset()         { *m = Resp{} }
func (m *Resp) String() string { return proto.CompactTextString(m) }
func (*Resp) ProtoMessage()    {}
func (*Resp) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae6ce81ad544face, []int{28}
}

func (m *Resp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Resp.Unmarshal(m, b)
}
func (m *Resp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Resp.Marshal(b, m, deterministic)
}
func (m *Resp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Resp.Merge(m, src)
}
func (m *Resp) XXX_Size() int {
	return xxx_messageInfo_Resp.Size(m)
}
func (m *Resp) XXX_DiscardUnknown() {
	xxx_messageInfo_Resp.DiscardUnknown(m)
}

var xxx_messageInfo_Resp proto.InternalMessageInfo

func (m *Resp) GetCode() Code {
	if m != nil {
		return m.Code
	}
	return Code_Success
}

func (m *Resp) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func init() {
	proto.RegisterEnum("api.Code", Code_name, Code_value)
	proto.RegisterType((*ReqConf)(nil), "api.ReqConf")
	proto.RegisterType((*RespConf)(nil), "api.RespConf")
	proto.RegisterType((*ReqDatabases)(nil), "api.ReqDatabases")
	proto.RegisterType((*RespDatabases)(nil), "api.RespDatabases")
	proto.RegisterType((*ReqForms)(nil), "api.ReqForms")
	proto.RegisterType((*RespForms)(nil), "api.RespForms")
	proto.RegisterType((*ReqCreateDatabase)(nil), "api.ReqCreateDatabase")
	proto.RegisterType((*RespDatabase)(nil), "api.RespDatabase")
	proto.RegisterType((*ReqCreateForm)(nil), "api.ReqCreateForm")
	proto.RegisterType((*ReqCreateKey)(nil), "api.ReqCreateKey")
	proto.RegisterType((*ReqCreateIndex)(nil), "api.ReqCreateIndex")
	proto.RegisterType((*ReqPutD)(nil), "api.ReqPutD")
	proto.RegisterType((*RespPutD)(nil), "api.RespPutD")
	proto.RegisterType((*ReqSetD)(nil), "api.ReqSetD")
	proto.RegisterType((*RespSetD)(nil), "api.RespSetD")
	proto.RegisterType((*ReqGetD)(nil), "api.ReqGetD")
	proto.RegisterType((*RespGetD)(nil), "api.RespGetD")
	proto.RegisterType((*ReqPut)(nil), "api.ReqPut")
	proto.RegisterType((*RespPut)(nil), "api.RespPut")
	proto.RegisterType((*ReqSet)(nil), "api.ReqSet")
	proto.RegisterType((*RespSet)(nil), "api.RespSet")
	proto.RegisterType((*ReqGet)(nil), "api.ReqGet")
	proto.RegisterType((*RespGet)(nil), "api.RespGet")
	proto.RegisterType((*ReqSelect)(nil), "api.ReqSelect")
	proto.RegisterType((*RespSelect)(nil), "api.RespSelect")
	proto.RegisterType((*ReqRemove)(nil), "api.ReqRemove")
	proto.RegisterType((*ReqDelete)(nil), "api.ReqDelete")
	proto.RegisterType((*RespDelete)(nil), "api.RespDelete")
	proto.RegisterType((*Resp)(nil), "api.Resp")
}

func init() { proto.RegisterFile("api/rs.proto", fileDescriptor_ae6ce81ad544face) }

var fileDescriptor_ae6ce81ad544face = []byte{
	// 650 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x56, 0xdb, 0x6e, 0xd3, 0x4c,
	0x10, 0xfe, 0x13, 0xbb, 0x4d, 0x3c, 0x4d, 0xa3, 0xfe, 0x2b, 0x84, 0xac, 0xa2, 0x8a, 0x68, 0xaf,
	0x52, 0x90, 0x8c, 0x28, 0xd7, 0x5c, 0xd0, 0x94, 0x06, 0x54, 0x81, 0xaa, 0x35, 0x2a, 0xa2, 0x08,
	0x89, 0xad, 0x3b, 0x01, 0x4b, 0x8e, 0xed, 0xf8, 0x50, 0x91, 0x77, 0xe0, 0xa1, 0xd1, 0xec, 0xda,
	0x4e, 0x82, 0x62, 0xb9, 0xa5, 0x87, 0x3b, 0xcf, 0xcc, 0xce, 0x7c, 0x87, 0xd9, 0xc4, 0x86, 0x9e,
	0x8c, 0xfd, 0x17, 0x49, 0xea, 0xc4, 0x49, 0x94, 0x45, 0xcc, 0x90, 0xb1, 0xbf, 0xdb, 0xa7, 0xd4,
	0xa5, 0xcc, 0xa4, 0x4e, 0xea, 0xd8, 0x8b, 0xc2, 0x89, 0x8e, 0xb9, 0x05, 0x1d, 0x81, 0xb3, 0x51,
	0x14, 0x4e, 0xf8, 0x77, 0xe8, 0x0a, 0x4c, 0x63, 0x7a, 0x66, 0x7b, 0x60, 0x8e, 0xa2, 0x4b, 0xb4,
	0x5b, 0x83, 0xd6, 0xb0, 0x7f, 0x60, 0x39, 0x32, 0xf6, 0x1d, 0x4a, 0x08, 0x95, 0xd6, 0xe5, 0x70,
	0x62, 0xb7, 0x07, 0xad, 0xe1, 0x56, 0x55, 0x0e, 0x27, 0x42, 0xa5, 0xd9, 0x63, 0xd8, 0x7c, 0x9b,
	0x24, 0x1f, 0xd2, 0x1f, 0xb6, 0x31, 0x68, 0x0d, 0x2d, 0x51, 0x44, 0xbc, 0x0f, 0x3d, 0x81, 0xb3,
	0x23, 0x99, 0xc9, 0x0b, 0x99, 0x62, 0xca, 0x53, 0xd8, 0x26, 0xc4, 0x2a, 0xd1, 0x04, 0xfb, 0x1c,
	0xac, 0xea, 0xac, 0xdd, 0x1e, 0x18, 0xc3, 0xad, 0x83, 0x6d, 0x75, 0xa6, 0xcc, 0x8a, 0x45, 0xbd,
	0x96, 0x84, 0x43, 0x32, 0x67, 0xc7, 0x51, 0x32, 0x4d, 0x19, 0x87, 0x5e, 0xd9, 0xf0, 0x51, 0x4e,
	0x35, 0xae, 0x25, 0x56, 0x72, 0xdc, 0x03, 0x8b, 0x48, 0xea, 0x86, 0x06, 0x82, 0x4f, 0x61, 0x43,
	0x9d, 0x2b, 0xc8, 0xe9, 0x3a, 0x65, 0x84, 0xce, 0xd7, 0x92, 0x7a, 0x03, 0xff, 0xd3, 0x1a, 0x12,
	0x94, 0x19, 0x96, 0xe8, 0x8c, 0x81, 0xb9, 0xc4, 0x4a, 0x3d, 0x33, 0x1b, 0x3a, 0xa3, 0x68, 0x3a,
	0xc5, 0x30, 0x53, 0xe6, 0x5b, 0xa2, 0x0c, 0x79, 0x4c, 0xe6, 0x2e, 0xcc, 0x6c, 0xa2, 0xba, 0x0f,
	0xdd, 0xf2, 0x68, 0xb1, 0xc6, 0xbf, 0xac, 0xac, 0xca, 0xb5, 0xa4, 0x7f, 0xb7, 0x68, 0x7f, 0x05,
	0x6b, 0xd2, 0x77, 0x1d, 0x3f, 0x2b, 0x55, 0xed, 0xf5, 0xaa, 0x8c, 0x15, 0x55, 0x44, 0x93, 0x26,
	0x7f, 0x9a, 0xc7, 0x68, 0x9b, 0x4a, 0xc9, 0x76, 0x65, 0x2a, 0x25, 0x45, 0x55, 0xe6, 0x89, 0xba,
	0x5d, 0x9a, 0xcd, 0x09, 0xce, 0xaf, 0x45, 0x66, 0x57, 0x8f, 0x5f, 0x22, 0x54, 0xc5, 0xd4, 0x7f,
	0x82, 0x73, 0x37, 0x4b, 0x72, 0x2f, 0xcb, 0x13, 0x2c, 0x98, 0xad, 0xe4, 0x78, 0x06, 0xfd, 0x0a,
	0xf3, 0x7d, 0x78, 0x89, 0xbf, 0x1e, 0x04, 0xf5, 0xa5, 0xfa, 0xd1, 0x9e, 0xe6, 0xd9, 0x11, 0xdb,
	0x01, 0xe3, 0x04, 0xe7, 0x05, 0x0a, 0x3d, 0xb2, 0x47, 0xb0, 0x71, 0x26, 0x83, 0x5c, 0x4f, 0xee,
	0x09, 0x1d, 0xf0, 0xaf, 0xfa, 0xc7, 0xad, 0x7a, 0x1a, 0x6e, 0x86, 0x0d, 0x9d, 0x77, 0x32, 0xfd,
	0x49, 0x63, 0x69, 0x84, 0x29, 0xca, 0xb0, 0xf6, 0x22, 0x68, 0x3e, 0x2e, 0xde, 0x9c, 0x8f, 0xea,
	0xb9, 0x73, 0x3e, 0x4f, 0x14, 0x9f, 0xf1, 0x5a, 0x3e, 0xfc, 0xb3, 0x46, 0x1e, 0x5f, 0x03, 0x79,
	0x2d, 0xf5, 0x5a, 0xd4, 0x18, 0x36, 0xf5, 0x56, 0x6e, 0x7d, 0x07, 0x0a, 0xd2, 0xc6, 0x1a, 0x13,
	0xcd, 0x65, 0x13, 0xcf, 0x49, 0xa7, 0x5a, 0xea, 0xdd, 0x7b, 0xa8, 0xd5, 0xb8, 0xf8, 0xe0, 0x6a,
	0x08, 0xf2, 0xce, 0xd5, 0x9c, 0x2b, 0x35, 0xe3, 0xfb, 0x50, 0xc3, 0xcf, 0x34, 0xef, 0x71, 0x33,
	0xef, 0x9b, 0xdd, 0xa7, 0x2b, 0x7a, 0xf1, 0xcc, 0x5c, 0x0c, 0xd0, 0xbb, 0x3d, 0xed, 0x7d, 0xe8,
	0xea, 0x49, 0x51, 0xa2, 0x60, 0xca, 0xbf, 0xfb, 0x32, 0x29, 0xaa, 0x32, 0x8f, 0x00, 0xf4, 0x1e,
	0x14, 0x70, 0xb3, 0xa4, 0x51, 0x94, 0x17, 0x6f, 0xa3, 0x0d, 0xa1, 0x83, 0x85, 0x50, 0x63, 0xbd,
	0x50, 0x73, 0x45, 0xe8, 0x37, 0x25, 0x54, 0xe0, 0x34, 0xba, 0xc2, 0x7b, 0xd8, 0x8f, 0xf6, 0xf1,
	0x08, 0x03, 0xcc, 0xf0, 0x21, 0x7d, 0xfc, 0xa2, 0x7d, 0x2c, 0x80, 0xff, 0xc9, 0xc7, 0xba, 0xab,
	0xf1, 0x1a, 0x4c, 0x1a, 0xdd, 0x34, 0x74, 0xd1, 0xde, 0x5e, 0x6e, 0x7f, 0x56, 0xb4, 0xb1, 0x2d,
	0xe8, 0xb8, 0xb9, 0xe7, 0x61, 0x9a, 0xee, 0xfc, 0xc7, 0xba, 0x60, 0x1e, 0x4b, 0x3f, 0xd8, 0x69,
	0x1d, 0xee, 0x01, 0xf3, 0x42, 0x47, 0x5e, 0x60, 0xe2, 0x7b, 0x4e, 0xe0, 0x07, 0x73, 0x9a, 0x7b,
	0xd8, 0x11, 0xee, 0x29, 0x7d, 0x32, 0x5e, 0x6c, 0xaa, 0x2f, 0xc7, 0x57, 0x7f, 0x02, 0x00, 0x00,
	0xff, 0xff, 0xf8, 0xb7, 0xbd, 0xfd, 0x6e, 0x0a, 0x00, 0x00,
}
